### ISSUE TITLE
Passing extra argument is not working

### ISSUE THREAD

**Issue by jackmatt2** [dockyard/ember-async-button#43]
Ember: 1.11.1
Ember-Cli: 0.2.3

I just tried using the new syntax to allow extra arguments to be passed to the async-button action.

```javascript
{{async-button shipment  action="advise" default="Advise" pending="Advising..." rejected="Failed Try Again"}}
```

```
Uncaught Error: Assertion Failed: You can only pass attributes (such as name=value) not bare values to a helper for a View found in 'bom@component:async-button:'
```

**Comment by seawatts** [comment]
@jackmatt2 I'm getting this same error. Have you figured it out?

**Comment by jackmatt2** [comment]
@seawatts not yet.

**Comment by seawatts** [comment]
Darn. Everything works fine for me when I actually go to the page and use it. But when I run my tests I get that error.

**Comment by SeyZ** [comment]
Same problem. Any news?

**Comment by byelipk** [comment]
For me just doing `npm install ember-cli-async-button --save-dev` didn't pull down the most up-to-date version. 

I had to point my npm install to this github repo in order to get passing arguments functionality to work:

`npm install https://github.com/dockyard/ember-cli-async-button.git --save-dev`

**Comment by drspaniel** [comment]
Looks like this was fixed in a recent release

**Comment by seawatts** [comment]
:+1:
