### ISSUE TITLE
Errors in action callback promise are swallowed.

### ISSUE THREAD

**Issue by rwjblue** [dockyard/ember-async-button#48]
Adding a `.catch` handler to the callback promise, and not re-throwing the provided error leads to the error being swallowed (preventing the `error` action bubbling and states).  

https://github.com/dockyard/ember-cli-async-button/blob/master/addon/components/async-button.js#L79-L81

We should be doing something like:

```javascript
    .catch(function(error) {
      if (!_this.isDestroyed) {
        set(_this, 'textState', 'rejected');
      }

      throw error;
    });
```

**Comment by rwjblue** [comment]
The snippet above, should work properly, but I need to add a test.  Will try to make time to add a test and PR soon...

**Comment by drspaniel** [comment]
I don't think this is a real issue. Attaching a .then or a .catch doesn't mutate the original promise for other consumers (although it does have the side effect of executing your function at some point).
We wouldn't do anything with the resulting failed promise. @rwjblue reopen if you disagree

**Comment by rwjblue** [comment]
The error swallowing that I initially thought was being caused here, was actually the fault of Ember's default RSVP error handler that has subsequently been fixed.

:+1: - good analysis (that my initial hunch was wrong)

**Comment by jasonmit** [comment]
Ran into this today and I think attaching the catch w/o a rethrow will troll if devs are dependent on the uncaught rejection handler firing.  Because the catch the component attaches, it was technically handled and therefore will not hit the uncaught handler.

I ended up forking to include the rethrow while we determine a path off ember-async-button since it's deprecated, but figured I'd leave this comment here to avoid others being trolled.
